<a href="https://colab.research.google.com/github/DonRoboto/AprendizajeAutomatizado/blob/master/BayesianNetwork_v1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [20]:
!pip install pomegranate


In [50]:

import numpy as np
import pandas as pd
from sklearn import datasets
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix

import math
from pomegranate import *


In [85]:
df = pd.read_csv("iris.csv") 

df.head()

s_length  s_width  p_length  p_width  variety
0       5.1      3.5       1.4      0.2        0
1       4.9      3.0       1.4      0.2        0
2       4.7      3.2       1.3      0.2        0
3       4.6      3.1       1.5      0.2        0
4       5.0      3.6       1.4      0.2        0

In [86]:
def jitter(a_series, noise_reduction=1000000):
    return (np.random.random(len(a_series))*a_series.std()/noise_reduction)-(a_series.std()/(2*noise_reduction))



df['Ds_length'] = pd.qcut(df['s_length']+ jitter(df['s_length']), 10, labels=False)
df['Ds_width'] = pd.qcut(df['s_width']+ jitter(df['s_width']), 10, labels=False)
df['Dp_length'] = pd.qcut(df['p_length']+ jitter(df['p_length']), 10, labels=False)
df['Dp_width'] = pd.qcut(df['p_width']+ jitter(df['p_width']), 10, labels=False)



In [24]:
df.head()


s_length  s_width  p_length  ...  Ds_width  Dp_length  Dp_width
0       5.1      3.5       1.4  ...         8          1         0
1       4.9      3.0       1.4  ...         4          0         2
2       4.7      3.2       1.3  ...         6          0         0
3       4.6      3.1       1.5  ...         5          2         1
4       5.0      3.6       1.4  ...         8          1         1

[5 rows x 9 columns]

In [87]:
df_model = df.loc[:,['variety','Ds_length', 'Ds_width', 'Dp_length', 'Dp_width' ]]

In [40]:
df_model.head()

variety  Ds_length  Ds_width  Dp_length  Dp_width
0        0          2         8          1         0
1        0          1         4          0         2
2        0          0         6          0         0
3        0          0         5          2         1
4        0          2         8          1         1

In [88]:
X = df_model.loc[:,['Ds_length', 'Ds_width', 'Dp_length', 'Dp_width']]
y = df_model.loc[:,['variety']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [89]:
X_train_model = pd.concat([y_train, X_train], axis=1)

model = BayesianNetwork.from_samples(X_train_model, state_names=X_train_model.columns.values, algorithm='exact')


In [90]:
X_test_model = pd.concat([y_test, X_test], axis=1)
X_test_model['variety']=None


In [80]:
X_test_model.values


array([[None, 6, 2, 6, 4],
       [None, 4, 9, 3, 2],
       [None, 9, 1, 9, 9],
       [None, 5, 3, 5, 6],
       [None, 8, 2, 6, 5],
       [None, 3, 7, 2, 2],
       [None, 4, 3, 3, 4],
       [None, 8, 5, 7, 9],
       [None, 6, 0, 5, 6],
       [None, 5, 1, 4, 4],
       [None, 7, 6, 7, 8],
       [None, 0, 4, 1, 0],
       [None, 3, 8, 0, 1],
       [None, 1, 5, 2, 0],
       [None, 2, 9, 1, 2],
       [None, 6, 7, 6, 6],
       [None, 7, 4, 8, 8],
       [None, 3, 0, 3, 3],
       [None, 4, 3, 5, 5],
       [None, 7, 2, 8, 9],
       [None, 0, 7, 2, 2],
       [None, 6, 5, 6, 7],
       [None, 1, 7, 2, 2],
       [None, 7, 2, 8, 8],
       [None, 9, 9, 9, 8],
       [None, 8, 4, 7, 9],
       [None, 8, 0, 9, 7],
       [None, 8, 6, 9, 9],
       [None, 0, 3, 1, 2],
       [None, 0, 6, 2, 1],
       [None, 0, 8, 0, 0],
       [None, 4, 9, 1, 2],
       [None, 8, 5, 5, 5],
       [None, 1, 8, 2, 0],
       [None, 0, 6, 0, 1],
       [None, 7, 1, 7, 7],
       [None, 7, 6, 5, 6],
 

In [91]:
predict = model.predict_proba(X_test_model.values)

In [94]:
y_model = model.predict(X_test_model.values)

y_model



[array([1, 6, 2, 6, 4], dtype=object),
 array([0, 4, 9, 3, 2], dtype=object),
 array([1, 9, 1, 9, 9], dtype=object),
 array([1, 5, 3, 5, 6], dtype=object),
 array([1, 8, 3, 6, 5], dtype=object),
 array([0, 3, 7, 2, 2], dtype=object),
 array([1, 4, 3, 3, 4], dtype=object),
 array([1, 9, 5, 7, 9], dtype=object),
 array([1, 6, 0, 5, 6], dtype=object),
 array([1, 5, 2, 4, 4], dtype=object),
 array([1, 7, 6, 7, 8], dtype=object),
 array([0, 0, 4, 0, 0], dtype=object),
 array([0, 3, 8, 0, 1], dtype=object),
 array([0, 1, 6, 1, 0], dtype=object),
 array([0, 2, 9, 1, 2], dtype=object),
 array([1, 7, 7, 6, 6], dtype=object),
 array([1, 7, 5, 9, 9], dtype=object),
 array([1, 4, 0, 3, 3], dtype=object),
 array([1, 4, 2, 5, 4], dtype=object),
 array([1, 7, 2, 8, 8], dtype=object),
 array([0, 0, 6, 2, 0], dtype=object),
 array([1, 6, 4, 6, 7], dtype=object),
 array([0, 1, 8, 2, 3], dtype=object),
 array([1, 7, 2, 8, 8], dtype=object),
 array([1, 9, 9, 9, 8], dtype=object),
 array([1, 8, 4, 7, 9], d

In [95]:
def Extract(lst):
    return list(list(zip(*lst))[0])

y_pred = Extract(y_model)

y_true = y_test

In [96]:
cf = confusion_matrix(y_true, y_pred)

In [97]:
cf

array([[19,  0],
       [ 0, 31]])